#!/bin/bash
echo start script
echo export URI
export ROS_MASTER_URI=http://brainnode:11311
echo start roscore
roscore >/dev/null 2>&1 &
echo start discovery
rosrun master_discovery_fkie master_discovery >/dev/null 2>&1 &
echo start sync
rosrun master_sync_fkie master_sync >/dev/null 2>&1 &

